assistant_prefill: ''
ds_kwargs:
  name: lamp_citation_ood_train
  path: ./data_p13n/hf_datasets_profile_split/LaMP/citation_ood_train
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# Instruction: 
  Identify the most relevant reference for the listed publication by the researcher. Select the reference paper that is most closely related to the researcher's work.

  # Paper Title: 
  {paper_title}

  # Options: 
  {options_str}

  # Output Format: 
  Just answer with [1] or [2] without explanation.
  
  # Answer:"
