assistant_prefill: ''
ds_kwargs:
  name: lamp_tweet_ood_train
  path: ./data_p13n/hf_datasets_profile_split/LaMP/tweet_ood_train
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# Instruction: 
  Paraphrase the following text into tweet without any explanation before or after it.

  # Original Tweet: 
  {original_tweet}

  # Output Format: 
  Just answer the paraphrased tweet without further explanation.
  
  # Answer:"
