assistant_prefill: ''
ds_kwargs:
  name: prism_random_train
  path: ./data_p13n/hf_datasets_profile_split/PRISM/random_train
train_first_n: null
response_field: output
system_message: ''
task_description: 'Generate a personalized response to the user based on the profile and personality traits.'
prepand_profile: false

