assistant_prefill: ''
ds_kwargs:
  name: lamp_news_headline_ood_train
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/news_headline_train
train_first_n: null
response_field: output
system_message: ''
task_description: 'News article headline generation: Create a concise and engaging headline for news articles based on their content and key themes.'
user_prompt_template: "# Instruction: 
  Generate a headline for the following article.

  # Article: 
  {article}

  # Output Format: 
  Just answer the headline without further explanation.
  
  # Answer:"
