assistant_prefill: ''
ds_kwargs:
  name: opinionqa_ood_train
  path: ./data_p13n/hf_datasets_profile_split/OpinionQA/ood_train
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# Question: 
  {question}

  # Options:
  {options}

  # Output Format:
  Only output the character corresponding to your choice. Do not include any explanation or additional text.
  
  # Answer:"
