assistant_prefill: ''
ds_kwargs:
  name: lamp_tweet_random_test
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/tweet_random_test
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# User History:
  {profile_retrieval_k4}

  # Instruction:
  Paraphrase the following text into tweet without any explanation before or after it.
  
  # Original Tweet:
  {original_tweet}

  # Output Format:
  Just answer the paraphrased tweet without further explanation.
  
  # Answer:"
