assistant_prefill: ''
ds_kwargs:
  name: lamp_product_random_train
  path: ./data_p13n/hf_datasets_profile_split/LaMP/product_random_train
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# Instruction:
  What is the score of the following review on a scale of 1 to 5? 
  
  # Review:
  {review_text}

  # Output Format:
  Just answer with 1, 2, 3, 4, or 5 without further explanation.
  
  # Answer:"
