assistant_prefill: ''
ds_kwargs:
  name: EC_random_train
  path: ./data_p13n/hf_datasets_profile_split/EC/random_train
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# Article: 
  {article}

  # Instruction: 
  After reading the news article, write an essay (300-800 characters) summarizing your thoughts and feelings about the article.
  
  # Answer:"
