assistant_prefill: ''
ds_kwargs:
  name: opinionqa_ood_test
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/OpinionQA/ood_test
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# User Profile: 
  {profile_all_history}

  # Question: 
  {question}

  # Options: 
  {options}

  # Output Format: 
  Only output the character corresponding to your choice. Do not include any explanation or additional text.
  
  # Answer:"
