assistant_prefill: ''
ds_kwargs:
  name: longlamp_abstract_generation_random_train
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LongLaMP/abstract_generation_train
train_first_n: null
response_field: output
system_message: ''
task_description: 'Academic abstract generation: Create comprehensive abstracts for research papers based on titles and key research items, incorporating domain-specific knowledge and writing style.'
user_prompt_template: "# Instruction:
  Given the paper title and key items, generate an abstract for the paper.

  # Paper Title:
  {paper_title}

  # Output Format:
  Only output the abstract. Do not include any explanation or formatting.
  
  # Answer:"
