assistant_prefill: ''
ds_kwargs:
  name: RAG_lamp_news_headline_train
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/news_headline_train
train_first_n: null
response_field: output
retrieval_k:
- 1
system_message: ''
user_prompt_template: '# User History: {profile_retrieval_k}

  # Instruction: Generate a headline for the following article.

  # Article: {article}

  # Output Format: Just answer the headline without further explanation.

  # Answer:'
