assistant_prefill: ''
ds_kwargs:
  name: RAG_lamp_citation_ood_train
  path: ./data_p13n/hf_datasets_profile_split/LaMP/citation_ood_train
train_first_n: null
response_field: output
retrieval_k:
- 1
- 2
- 4
system_message: ''
user_prompt_template: '# User History: {profile_retrieval_k}

  # Instruction: Identify the most relevant reference for the listed publication by
  the researcher. Select the reference paper that is most closely related to the researcher''s
  work.

  # Paper Title: {paper_title}

  # Options: {options_str}

  # Output Format: Just answer with [1] or [2] without explanation.

  # Answer:'
