assistant_prefill: ''
ds_kwargs:
  name: opinionqa_ood_train
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/OpinionQA/train
train_first_n: null
response_field: output
system_message: ''
task_description: 'Opinion-based question answering: Answer multiple choice questions based on personal opinions, values, and demographic background rather than factual knowledge.'
user_prompt_template: "# Question: 
  {question}

  # Options:
  {options}

  # Output Format:
  Only output the character corresponding to your choice. Do not include any explanation or additional text.
  
  # Answer:"
