assistant_prefill: ''
ds_kwargs:
  name: lamp_scholarly_title_random_test
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/scholarly_title_random_test
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# User Profile:
  {profile_text}

  # User History:
  {profile_retrieval_k1}

  # Instruction:
  Generate a title for the following abstract of a paper.
  
  # Abstract:
  {abstract}

  # Output Format:
  Just answer the title without further explanation.
  
  # Answer:"
