assistant_prefill: ''
ds_kwargs:
  name: RAG_lamp_movie_train
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/movie_train
train_first_n: null
response_field: output
retrieval_k:
- 1
system_message: ''
user_prompt_template: '# User History: {profile_retrieval_k}

  # Instruction: Based on the user history, which tag does this movie relate to among
  the following tags?

  # Tags: [sci-fi, based on a book, comedy, action, twist ending, dystopia, dark comedy,
  classic, psychology, fantasy, romance, thought-provoking, social commentary, violence,
  true story]

  # Description: {description}

  # Output Format: Just answer with the tag name without further explanation.

  # Answer:'
