assistant_prefill: ''
ds_kwargs:
  name: lamp_news_headline_random_test
  path: ./data_p13n/hf_datasets_history_split_task_specific_profile_retrieval_v3/LaMP/news_headline_random_test
train_first_n: null
response_field: output
system_message: ''
user_prompt_template: "# User Profile:
  {profile_text}

  # User History:
  {profile_retrieval_k1}

  # Instruction:
  Generate a headline for the following article.
  
  # Article:
  {article}

  # Output Format:
  Just answer the headline without further explanation.
  
  # Answer:"
